FactoryBot.define do
  factory :note do
    title { Faker::Lorem.sentence(word_count: 3).chomp(".") }
    note_kind { "markdown" }
    detected_language { "pt-BR" }
    slug { nil }  # generated by model callback

    trait :deleted do
      deleted_at { Time.current }
    end

    trait :with_head_revision do
      after(:create) do |note|
        revision = create(:note_revision, note: note)
        note.update_columns(head_revision_id: revision.id)
      end
    end
  end
end
