default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: neura_md_development
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  queue:
    <<: *primary_development
    database: neura_md_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: neura_md_test
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("NEURAMD_DATABASE", "neura_md_production") %>
    username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("NEURAMD_CACHE_DATABASE", "neura_md_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("NEURAMD_QUEUE_DATABASE", "neura_md_production_queue") %>
    migrations_paths: db/queue_migrate
